version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: app_name
    container_name: app_name
    command: bash -c "gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    environment:
      - PROD=true
    env_file:
      - .env.prod
    ports:
      - 8000:8000
    volumes:
      - ./src:/fastapi_app_app/src:z
      - ./requirements.txt:/fastapi_app/requirements.txt:z
    depends_on:
      - db
    restart: always
